<?php

namespace Database\Seeders;

use App\Models\School;
use Illuminate\Database\Seeder;

class SchoolSeeder extends Seeder
{
    public function run(): void
    {
        $schools = [
            ['nama_sekolah' => 'SMPN 1 CIAMIS', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPN 2 CIAMIS', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPN 3 CIAMIS', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPN 4 CIAMIS', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPN 5 CIAMIS', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPN 6 CIAMIS', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPN 7 CIAMIS', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPN 8 CIAMIS', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPN 1 SADANANYA', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Sadananya'],
            ['nama_sekolah' => 'SMPN 1 SUKADANA', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Sukadana'],
            ['nama_sekolah' => 'SMPN 1 BAREGBEG', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Baregbeg'],
            ['nama_sekolah' => 'SMPN 2 BAREGBEG', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Baregbeg'],
            ['nama_sekolah' => 'SMPN 3 BAREGBEG', 'komisariat' => '1', 'status' => 'NEGERI', 'kecamatan' => 'Baregbeg'],
            ['nama_sekolah' => 'SMP TERPADU AL HASAN CIAMIS', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP TERPADU ARRISALAH', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP PLUS MAARIF NU CIAMIS', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPS PLUS BINA PANDU MANDIRI', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU RIYADLUL QUR\'AN', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP IT IRFANI QURANICPRENEUR BILINGUAL SCHOOL', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP TERPADU BABUSSALAM', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP AL HUDA TURALAK', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP AT TIBYAN', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU MUHAMMAD DANU FATHAHILLAH', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU DAARUL FALAAH', 'komisariat' => '1', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMPN 1 CIKONENG', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMPN 2 CIKONENG', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMPN 1 SINDANGKASIH', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Sindangkasih'],
            ['nama_sekolah' => 'SMPN 1 CIHAURBEUTI', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Cihaurbeuti'],
            ['nama_sekolah' => 'SMPN 2 CIHAURBEUTI', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Cihaurbeuti'],
            ['nama_sekolah' => 'SMPN 1 PANUMBANGAN', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Panumbangan'],
            ['nama_sekolah' => 'SMPN 2 PANUMBANGAN', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Panumbangan'],
            ['nama_sekolah' => 'SMPN 3 PANUMBANGAN', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Panumbangan'],
            ['nama_sekolah' => 'SMPN SATU ATAP 1 PANUMBANGAN', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Panumbangan'],
            ['nama_sekolah' => 'SMPN 1 SUKAMANTRI', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Sukamantri'],
            ['nama_sekolah' => 'SMPN 2 SUKAMANTRI', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Sukamantri'],
            ['nama_sekolah' => 'SMPN SATU ATAP 1 SUKAMANTRI', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Sukamantri'],
            ['nama_sekolah' => 'SMPN 1 PANJALU', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Panjalu'],
            ['nama_sekolah' => 'SMPN 2 PANJALU', 'komisariat' => '2', 'status' => 'NEGERI', 'kecamatan' => 'Panjalu'],
            ['nama_sekolah' => 'SMP IBNU SIENA CIKONENG CIAMIS', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Ciamis'],
            ['nama_sekolah' => 'SMP INSPIRASI', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMP ISLAM ASB MIFTAHUL ULUM', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMP ISLAM MAARIF NU CIKONENG', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMPS PLUS DARUL IHSAN', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMP TERPADU ISHLAHUL MUBTADIIN', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMP MUHAMMADIYAH CIKONENG', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMP PLUS MAARIF NU AL HIKMAH CIHAURBEUTI', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cihaurbeuti'],
            ['nama_sekolah' => 'SMP PLUS PERSIS PANUMBANGAN', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Panumbangan'],
            ['nama_sekolah' => 'SMP IT NURUL HUDA', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMP MIFTAHUL KHOER BOARDING SCHOOL', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU BOARDING SCHOOL AL JAOHAR', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMP PLUS ARRIYADHOH', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMP IT AL AMANAH', 'komisariat' => '2', 'status' => 'SWASTA', 'kecamatan' => 'Cikoneng'],
            ['nama_sekolah' => 'SMPN 1 KAWALI', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Kawali'],
            ['nama_sekolah' => 'SMPN 2 KAWALI', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Kawali'],
            ['nama_sekolah' => 'SMPN 3 KAWALI', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Kawali'],
            ['nama_sekolah' => 'SMPN 1 LUMBUNG', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Lumbung'],
            ['nama_sekolah' => 'SMPN 2 LUMBUNG', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Lumbung'],
            ['nama_sekolah' => 'SMPN 1 PANAWANGAN', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Panawangan'],
            ['nama_sekolah' => 'SMPN 2 PANAWANGAN', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Panawangan'],
            ['nama_sekolah' => 'SMPN 3 PANAWANGAN', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Panawangan'],
            ['nama_sekolah' => 'SMPN 4 PANAWANGAN', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Panawangan'],
            ['nama_sekolah' => 'SMPN 1 CIPAKU', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Cipaku'],
            ['nama_sekolah' => 'SMPN 2 CIPAKU', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Cipaku'],
            ['nama_sekolah' => 'SMPN 3 CIPAKU', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Cipaku'],
            ['nama_sekolah' => 'SMPN SATU ATAP 1 CIPAKU', 'komisariat' => '3', 'status' => 'NEGERI', 'kecamatan' => 'Cipaku'],
            ['nama_sekolah' => 'SMP IT NURUL HUDA UTSMANIYAH LUMBUNGSARI', 'komisariat' => '3', 'status' => 'SWASTA', 'kecamatan' => 'Lumbung'],
            ['nama_sekolah' => 'SMP MUHAMMADIYAH KAWALI', 'komisariat' => '3', 'status' => 'SWASTA', 'kecamatan' => 'Kawali'],
            ['nama_sekolah' => 'SMP PLUS MAARIF NU CIPAKU', 'komisariat' => '3', 'status' => 'SWASTA', 'kecamatan' => 'Cipaku'],
            ['nama_sekolah' => 'SMP MAARIF NU NURUL HIKMAH', 'komisariat' => '3', 'status' => 'SWASTA', 'kecamatan' => 'Kawali'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU NUURUSSALAAM', 'komisariat' => '3', 'status' => 'SWASTA', 'kecamatan' => 'Kawali'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU AS SULTHONIAH', 'komisariat' => '3', 'status' => 'SWASTA', 'kecamatan' => 'Kawali'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU ANHARUL ULUM', 'komisariat' => '3', 'status' => 'SWASTA', 'kecamatan' => 'Kawali'],
            ['nama_sekolah' => 'SMP CALISTUNG NUSANTARA', 'komisariat' => '3', 'status' => 'SWASTA', 'kecamatan' => 'Kawali'],
            ['nama_sekolah' => 'SMPN 1 RAJADESA', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMPN 2 RAJADESA', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMPN 3 RAJADESA', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMPN 4 RAJADESA', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMPN 5 RAJADESA', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMPN 6 RAJADESA', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMPN 1 JATINAGARA', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Jatinagara'],
            ['nama_sekolah' => 'SMPN 2 JATINAGARA', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Jatinagara'],
            ['nama_sekolah' => 'SMPN SATU ATAP 1 JATINAGARA', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Jatinagara'],
            ['nama_sekolah' => 'SMPN 1 RANCAH', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rancah'],
            ['nama_sekolah' => 'SMPN 2 RANCAH', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rancah'],
            ['nama_sekolah' => 'SMPN 3 RANCAH', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rancah'],
            ['nama_sekolah' => 'SMPN 4 RANCAH', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Rancah'],
            ['nama_sekolah' => 'SMPN 1 TAMBAKSARI', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Tambaksari'],
            ['nama_sekolah' => 'SMPN 2 TAMBAKSARI', 'komisariat' => '4', 'status' => 'NEGERI', 'kecamatan' => 'Tambaksari'],
            ['nama_sekolah' => 'SMP TERPADU AL MUAAWANAH RAJADESA', 'komisariat' => '4', 'status' => 'SWASTA', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMP IT MIFTAHUL HUDA II', 'komisariat' => '4', 'status' => 'SWASTA', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMP PLUS MAARIF AL MUSHLIHUUN', 'komisariat' => '4', 'status' => 'SWASTA', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMP MAARIF NU JATINAGARA', 'komisariat' => '4', 'status' => 'SWASTA', 'kecamatan' => 'Jatinagara'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU MIFTAHUL HUDA II AN NAWAWI', 'komisariat' => '4', 'status' => 'SWASTA', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMP MAARIF NU AL HUSAEINIYAH', 'komisariat' => '4', 'status' => 'SWASTA', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMP MANARUL HUDA', 'komisariat' => '4', 'status' => 'SWASTA', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU AR ROFII JATILUHUR', 'komisariat' => '4', 'status' => 'SWASTA', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMP IT SAADATUL ULFAH', 'komisariat' => '4', 'status' => 'SWASTA', 'kecamatan' => 'Rajadesa'],
            ['nama_sekolah' => 'SMPN 1 CISAGA', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Cisaga'],
            ['nama_sekolah' => 'SMPN 2 CISAGA', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Cisaga'],
            ['nama_sekolah' => 'SMPN 3 CISAGA', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Cisaga'],
            ['nama_sekolah' => 'SMPN 1 CIMARAGAS', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Cimaragas'],
            ['nama_sekolah' => 'SMPN 1 CIDOLOG', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Cidolog'],
            ['nama_sekolah' => 'SMPN 1 PAMARICAN', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Pamarican'],
            ['nama_sekolah' => 'SMPN 2 PAMARICAN', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Pamarican'],
            ['nama_sekolah' => 'SMPN 3 PAMARICAN', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Pamarican'],
            ['nama_sekolah' => 'SMPN 4 PAMARICAN', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Pamarican'],
            ['nama_sekolah' => 'SMPN 2 SUKADANA', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Sukadana'],
            ['nama_sekolah' => 'SMPN 1 CIJEUNGJING', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMPN 2 CIJEUNGJING', 'komisariat' => '5', 'status' => 'NEGERI', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU MAARIF AL BARKAH', 'komisariat' => '5', 'status' => 'SWASTA', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMPS DAARUL FALAH CIJEUNGJING', 'komisariat' => '5', 'status' => 'SWASTA', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU NURUSSALAM', 'komisariat' => '5', 'status' => 'SWASTA', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU MAGNA SHOFA', 'komisariat' => '5', 'status' => 'SWASTA', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMP PASUNDAN SIDAMULIH', 'komisariat' => '5', 'status' => 'SWASTA', 'kecamatan' => 'Sidamulih'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU NURUL HUDA', 'komisariat' => '5', 'status' => 'SWASTA', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMP MAARIF NU CIPASUNG', 'komisariat' => '5', 'status' => 'SWASTA', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU AS SHOFA CIJEUNGJING', 'komisariat' => '5', 'status' => 'SWASTA', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU MIFTAHUN NIDZOM CIJEUNGJING', 'komisariat' => '5', 'status' => 'SWASTA', 'kecamatan' => 'Cijeungjing'],
            ['nama_sekolah' => 'SMPN 1 BANJARSARI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMPN 2 BANJARSARI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMPN 3 BANJARSARI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMPN 4 BANJARSARI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMPN 5 BANJARSARI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMPN 6 BANJARSARI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMPN 7 BANJARSARI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMPN SATU ATAP 1 BANJARSARI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMPN 1 LAKBOK', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Lakbok'],
            ['nama_sekolah' => 'SMPN 2 LAKBOK', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Lakbok'],
            ['nama_sekolah' => 'SMPN 3 LAKBOK', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Lakbok'],
            ['nama_sekolah' => 'SMPN 1 PURWADADI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Purwadadi'],
            ['nama_sekolah' => 'SMPN 2 PURWADADI', 'komisariat' => '6', 'status' => 'NEGERI', 'kecamatan' => 'Purwadadi'],
            ['nama_sekolah' => 'SMP TERPADU DAMPASAN', 'komisariat' => '6', 'status' => 'SWASTA', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMP PLUS PASAWAHAN', 'komisariat' => '6', 'status' => 'SWASTA', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMP MUHAMMADIYAH BANJARSARI', 'komisariat' => '6', 'status' => 'SWASTA', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMP PLUS AL MUGNI', 'komisariat' => '6', 'status' => 'SWASTA', 'kecamatan' => 'Banjarsari'],
            ['nama_sekolah' => 'SMP MAARIF NU LAKBOK', 'komisariat' => '6', 'status' => 'SWASTA', 'kecamatan' => 'Lakbok'],
            ['nama_sekolah' => 'SMP PLUS MAARIF NU PURWADADI', 'komisariat' => '6', 'status' => 'SWASTA', 'kecamatan' => 'Purwadadi'],
            ['nama_sekolah' => 'SMP ISLAM TERPADU RIYADLUL KHOER CITUUR BANJARSARI', 'komisariat' => '6', 'status' => 'SWASTA', 'kecamatan' => 'Banjarsari'],
        ];

        foreach ($schools as $school) {
            School::updateOrCreate(
                ['nama_sekolah' => $school['nama_sekolah']],
                $school
            );
        }
    }
}
